name = "clt-ev-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-11-01"

[vars]
CHARGEPOINT_API_URL = "https://webservices.chargepoint.com/webservices/chargepoint/services/5.0"

[[d1_databases]]
binding = "DB"
database_name = "clt-ev-db"
database_id = "0a6d6c8f-7705-4f34-a8ee-65d480cd790b"

[[r2_buckets]]
binding = "R2"
bucket_name = "clt-ev-archive"

[triggers]
crons = ["*/30 * * * *", "0 * * * *", "0 6 * * *"]
